### ISSUE TITLE
GTA:SA no longer works

### ISSUE THREAD

**Issue by Ufeldraku** [mradermaxlol/wine-patched-nine#1]
As title says, GTA SA no longer works, plus, a lot o ntoskrnl fixmes messages are spitted in the terminal

**Comment by mradermaxlol** [comment]
@Ufeldraku very goddamn informative. With which options are you using Wine? What's your version of the latter - 1.9.9? Staging+Nine or Vanilla+Nine? Logs?

And, actually, this is the wrong issue tracker - report to @sarnex repos' issue tracker/s as this repo is just a github container of his source.

**Comment by Ufeldraku** [comment]
I'm so sorry, I fixed it by deleting my old wine prefix.
